name: ğŸš€ Deploy Backend to Server

on:
  push:
    branches:
      - DEPLOY  # Se ejecuta solo cuando hagas push al main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clonar repositorio
        uses: actions/checkout@v4

      - name: ğŸ‹ Iniciar sesiÃ³n en Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: ğŸ—ï¸ Construir imagen Docker
        run: docker build -t daviddominguez11/poolcenter-backend:latest .

      - name: ğŸ“¦ Subir imagen a Docker Hub
        run: docker push daviddominguez11/poolcenter-backend:latest

      - name: âš¡ Desplegar en el servidor remoto
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/test1/Backend_ISoftware1
            docker compose pull
            docker compose down
            docker compose up -d
            docker image prune -f
