name: ğŸš€ Deploy Backend to Server

on:
  push:
    branches:
      - DEPLOY  # Se ejecuta solo cuando hagas push al main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Clonar repositorio
        uses: actions/checkout@v4

      - name: ğŸ‹ Iniciar sesiÃ³n en Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: ğŸ—ï¸ Construir imagen Docker
        run: docker build -t ${{ secrets.IMAGE_NAME }}:latest .

      - name: ğŸ“¦ Subir imagen a Docker Hub
        run: docker push ${{ secrets.IMAGE_NAME }}:latest

      - name: âš¡ Desplegar en el servidor remoto
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.REMOTE_APP_PATH }}
            docker compose pull
            docker compose down
            docker compose up -d
            docker image prune -f

