name: ðŸš€ Deploy in Server

on:
  push:
    branches:
      - DEPLOY

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Actualizar cÃ³digo en el servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/test1/Backend_ISoftware1
            echo "ðŸŒ€ Actualizando cÃ³digo con git pull..."
            git pull origin DEPLOY
            echo "âœ… git pull exitoso."
            echo "ðŸ§± Reconstruyendo contenedores..."
            docker compose down -v
            docker compose up -d
            docker image prune -f
            docker ps
            echo "âœ… Deploy completado exitosamente"
